[tool.poetry]
name = "Image Indexing Project "
version = "0.1.0"
description = ""
authors = [
    "Salem Fradi <salemaziz.fradi@supcom.tn>",
    "Dhia Elhak Ezzeddini <dhiaelhak.ezzeddini@supcom.tn>"
]
license = "MIT"
readme = "README.md"